# Generated by Django 4.2.5 on 2023-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.SmallIntegerField(db_index=True, max_length=6),
        ),
    ]
